default:
    extensions:
      Behat\Symfony2Extension:
          kernel:
              env: "test"
              debug: true
      Behat\MinkExtension:
          base_url: http://localhost/symfony_jenkins/web/app_dev.php
          browser_name: firefox
          javascript_session: selenium2
          show_auto: true
          show_cmd: firefox
          sessions:
              default:
                  symfony2: ~
              selenium2:
                  selenium2:
                      browser: firefox
                      capabilities:
                          chrome:
                              switches:
                                  - "--headless"
                                  - "--disable-gpu"
                                  - "--window-size=1920,1080"
                                  - "--no-sandbox"
    suites:
        app:
          type: symfony_bundle
          bundle: AppBundle
          mink_session: selenium2
          contexts:
              - AppBundle\Features\Bootstrap\FeatureContext:
                  container: '@service_container'
                  entityManager: "@doctrine.orm.default_entity_manager"